### ISSUE TITLE
www.pybaq.co

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/django-quilla-web#102]
Cuando uno escribe https://www.pybaq.co/ El mensaje mostrado es de cloudfare

![screenshot_20171105_124005](https://user-images.githubusercontent.com/1175402/32417558-604020f6-c229-11e7-905a-d513b8e420a7.png)

**Comment by javierdaza** [comment]
Muchas gracias @Scot3004  
Veré como hacer la redirección del subdominio www a https://pybaq.co/

**Comment by GudarJs** [comment]
https://help.github.com/articles/setting-up-an-apex-domain-and-www-subdomain/

**Comment by javierdaza** [comment]
Hecho
