### ISSUE TITLE
Personalizar 404

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/django-quilla-web#103]
Se veria muy lindo si se crea un 404 personalizado en lugar de mostrar el de github pages, esto se logra creando un archivo llamado 404.html en el directorio raiz

![screenshot_20171105_130216](https://user-images.githubusercontent.com/1175402/32417580-a0255600-c229-11e7-8a8e-9d8ccd76e6d6.png)

**Comment by javierdaza** [comment]
Interesante. 
¿ Alguna plantilla divertida o graciosa de sugerencia @Scot3004 ?

**Comment by andresperezcera** [comment]
http://cdn2.hubspot.net/hubfs/53/404-error-page-examples.jpeg

**Comment by andresperezcera** [comment]
Desafortunadamente es necesario comprarla, la compro?

https://www.istockphoto.com/photo/web-message-gm474645684-64819465

**Comment by andresperezcera** [comment]
mas aquí, muchas pueden recrearse desde cero con algunas varaciones:

https://www.istockphoto.com/photos/error-404?excludenudity=true&mediatype=photography&phrase=error%20404&sort=mostpopular

**Comment by andresperezcera** [comment]
Otro encontrado en codepen:

https://codepen.io/MartijnBrands/pen/eZNxPN

**Comment by javierdaza** [comment]
El de code pen esta mundial! Usemos ese. ¿Supongo que la licencia es Creative Commons?

**Comment by andresperezcera** [comment]
https://blog.codepen.io/legal/licensing/

**Comment by Scot3004** [comment]
![imagen](https://user-images.githubusercontent.com/1175402/36816389-932b0774-1cab-11e8-9056-ffe6cf0f07e1.png)
Debido a que la página cuenta con sus estilos propios y que el css se haria mas pesado con webpack, se agregan en head los estilos.
