### ISSUE TITLE
Aviso sobre el uso de cookies en la web

### ISSUE THREAD

**Issue by javierdaza** [PyBAQ/django-quilla-web#105]
El aviso debe aparecer solo la primera vez que el usuario entra a la pagina. Debe poder ocultarse/cerrarse.

**Comment by Scot3004** [comment]
Se requiere definir una política de uso de cookies en una página donde se detalle exactamente que se hará con ellas, por ejemplo como se usa la cookie de google analytics en este caso.

Dentro de la implementación del popup estaba considerando esta opción: https://cookieconsent.insites.com/

**Comment by javierdaza** [comment]
Sobre las políticas de uso había pensado que podemos guiarnos de la información que aparece en **librosweb.es**: Ejemplos:

- [Condiciones](http://librosweb.es/sitio/condiciones)
- [Privacidad](http://librosweb.es/sitio/privacidad)

¡Buena opción para la implementación!

**Comment by javierdaza** [comment]
Se debe hacer un hard refresh para ver el aviso de osano pero ya funciona
