### ISSUE TITLE
Error de instalación

### ISSUE THREAD

**Issue by Xaraxx** [PyBAQ/django-quilla-web#111]
Acabado de instalar lektor en Ubuntu 14.04 

No se puede ejecutar usando lektor server -f webpack
![imagen](https://user-images.githubusercontent.com/29824698/36648666-5ad7317a-1a64-11e8-99d8-52f2938a5027.png)

![imagen](https://user-images.githubusercontent.com/29824698/36648676-869b11be-1a64-11e8-8a3d-0637d845397e.png)

**Comment by javierdaza** [comment]
1. Te aconsejo usar un virtual environment.
2. Es mejor que copies los errores con markdown para poder ayudar a buscar una solución
3. Este proyecto usa python 2.7. ¿Estas usando esta versión?

**Comment by Xaraxx** [comment]
1. Ok
2. Ok 
3. Si señor

**Comment by javierdaza** [comment]
Bro ¿ @Scot3004 puedes ayudar a Sara con la instalación?

**Comment by Scot3004** [comment]
Si, veremos que se puede hacer.

**Comment by GudarJs** [comment]
Algun update con este issue?

**Comment by guzmand** [comment]
@Xaraxx Porfa intenta hacer un pull e intentar correr el servidor de nuevo.

**Comment by javierdaza** [comment]
Esto es consecuencia de la falta de un manual de instalación en el README. Ver issue #120

**Comment by Scot3004** [comment]
#120 ya fue resuelto y no pude replicar la incidencia
