### ISSUE TITLE
*Build failing* en travis por PR de emojis

### ISSUE THREAD

**Issue by javierdaza** [PyBAQ/django-quilla-web#114]
*Build failing*

@GudarJs  el PR de los emoticones no deja hacer el build.
`AttributeError: 'Builder' object has no attribute 'build_flags'`

**Comment by GudarJs** [comment]
Fixed: #115 El problema era de versiones, tal vez antes funcionaba en una versión anterior de lektor, pero como no estábamos especificando una versión, travis usaba la mas reciente, lo que pudo hacer que se rompiese la pagina.

**Comment by Scot3004** [comment]
Creo que #111 también tiene que ver con la versión de lektor
