### ISSUE TITLE
Como instalar el proyecto en el README

### ISSUE THREAD

**Issue by javierdaza** [PyBAQ/django-quilla-web#120]
Faltan los pasos de como instalar el proyecto desde cero para los nuevos colaboradores. Preferiblemente ubicarlo en el README.md

**Comment by andresperezcera** [comment]
Yo me encargaré de la guía en windows, incluyendo el linux subsystem

**Comment by Scot3004** [comment]
ah bueno, voy a subir lo que llevo

**Comment by Scot3004** [comment]
Veni, entonces @andresperezcera te encargaras del resto, para reasignar este issue?

**Comment by andresperezcera** [comment]
@Scot3004 Si señor, ya le estoy trabajando, voy a publicarlo sin docker

**Comment by Scot3004** [comment]
Bro, mandala, de todos modos para eso tenemos #146, de hecho, en el momento que se resuelva ese el que cree ese PR es el responsable de agregar la guia de uso (instalación por docker)
