### ISSUE TITLE
Agregar rel="nofollow" a enlaces sociales

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/django-quilla-web#123]

**Comment by javierdaza** [comment]
¿Cuál es el propósito de este issue? 
Creo que el target _blank se utiliza en enlaces que no hagan parte de la misma marca (ej: enlace que apunte a una cuenta de facebook de python berlin)

**Comment by Scot3004** [comment]
Estoy de acuerdo con gudar, sin embargo agrego que deberia tener rel="nofollw"

**Comment by GudarJs** [comment]
https://sergioramirez.org/que-rel-nofollow-para-que-sirve/
https://support.google.com/webmasters/answer/96569?hl=es

**Comment by javierdaza** [comment]
Close by inactivity
