### ISSUE TITLE
Las URLs del sitio deben ser en español

### ISSUE THREAD

**Issue by javierdaza** [PyBAQ/django-quilla-web#125]
Para distinguirlas, de cuando se tenga, la versión en inglés

**Comment by Scot3004** [comment]
Para lo que propones primero debemos definir el flujo de trabajo para la internacionalización, ten en cuenta que hay que considerar también los blogs post, si se tendrá versión traducida de ellos o no.
Encontré esto leyendo sobre el tema: https://github.com/numericube/lektor-i18n-plugin.

**Comment by javierdaza** [comment]
Se puede contar como base la página de la pycon Colombia 2018. https://2018.pycon.co/

Sobre los artículos, podemos pensar en lo más cómodo para nosotros. Por ahora creo que lo mas sencillo y coherente que imagino sería tener artículos distintos, es decir, no todos los artículos de español se traducirían. ¿Qué opinas?

**Comment by Scot3004** [comment]
Estoy de acuerdo, aunque lo cierto es que aun no se como se portara el plugin de i18n si no hay articulos configurados.

**Comment by javierdaza** [comment]
¿Entonces de tarea quedaría pensar en 1 artículo en inglés? O podemos probar el plugin

**Comment by andresperezcera** [comment]
Después de terminar la sección de proyectos

**Comment by Scot3004** [comment]
Esta tarea se desagrega en:
#209, #210, #211, #212
