### ISSUE TITLE
No se ve la imagen de portada en localhost

### ISSUE THREAD

**Issue by GudarJs** [PyBAQ/django-quilla-web#136]
# Incidente sitio web python Barranquilla
La imagen de la portada se daño en localhost (por lo menos en mi pc).

## Comportamiento esperado
![image](https://user-images.githubusercontent.com/8474029/38545005-a401e8be-3c6e-11e8-9425-5806925cbec8.png)

## Comportamiento actual
![image](https://user-images.githubusercontent.com/8474029/38544950-75713b8a-3c6e-11e8-863d-6f9bc7afab66.png)

## Pasos para reproducir el error

1. Clone el repositorio en mi computador.
2. Ejecute `lektor server` como esta en [contribuir-blog-python-barranquilla](https://pybaq.co/blog/contribuir-blog-python-barranquilla/)
3. Entre a localhost:5000.

**Comment by GudarJs** [comment]
Parser de markdown a html que usa flask: https://github.com/lepture/mistune/issues/137
La solucion segun el issue es actualizar a la version 0.8.3 pero flask usa la 0.7 https://github.com/lektor/lektor/blob/master/setup.py, por lo que o se sube un pr a flask para actualizar la versión o no se puede usar los enlaces en formato html desde una pagina con contenido en markdown.

**Comment by javierdaza** [comment]
El comando completo es `lektor server -f webpack`
 ¿Has probado con ese?

**Comment by GudarJs** [comment]
Tampoco funcionan los enlaces de contacto de los organizadores 
![image](https://user-images.githubusercontent.com/8474029/38563904-9837b222-3ca3-11e8-8ddf-ea382bacdc8b.png)

**Comment by Scot3004** [comment]
@GudarJs nos regalas un update sobre este issue, a ver si se relaciona con webpack y cerrarlo, por que realmente no puedo reproducirlo

**Comment by Scot3004** [comment]
No se puede replicar, ademas que webpack fue eliminado por lo que es muy probable que no vuelva a suceder
