### ISSUE TITLE
Emojis gigantes 😰

### ISSUE THREAD

**Issue by GudarJs** [PyBAQ/django-quilla-web#137]
# Incidente sitio web python Barranquilla

## Comportamiento esperado

Los emojis deberian verse de un tamaño proporcional al texto.

## Comportamiento actual

![image](https://user-images.githubusercontent.com/8474029/38547611-1b63a9e6-3c75-11e8-806b-bb159056939c.png)

**Comment by GudarJs** [comment]
Corregido al ejecutar `lektor server -f webpack`.
Pd: Aunque en el readme esta bien el comando, se debe editar el articulo de como contribuir al blog ya que muestra el comando `lektor server`

**Comment by Scot3004** [comment]
Buen post data, pero si hay un issue y es de documentación

**Comment by GudarJs** [comment]
Fixed in #139
