### ISSUE TITLE
Agregar botones para compartir los articulos en redes sociales

### ISSUE THREAD

**Issue by GudarJs** [PyBAQ/django-quilla-web#142]

**Comment by Scot3004** [comment]
https://webdevtrick.com/css-fixed-social-media-sidebar/

**Comment by javierdaza** [comment]
Estaba pensando en que los botones quedaran fijos en una ubicación de la página. Algo como esto 

<img width="821" alt="Captura de Pantalla 2020-03-06 a la(s) 4 23 42 p  m" src="https://www.uiuxstream.com/wp-content/uploads/Static-social-share-buttons-for-websites-and-blog-sidebar-with-showhide-button.jpg">

**Comment by Scot3004** [comment]
Que tal la apariencia de estos iconos?
https://www.w3schools.com/howto/howto_css_sticky_social_bar.asp

**Comment by javierdaza** [comment]
Se ven bien @Scot3004 .Diría yo que las plataformas más relevantes son Facebook, Twitter y Linkedin. Ya Instagram y Youtube no lo se

**Comment by Scot3004** [comment]
De hecho ya tengo esas 3 en HTML y con databags solo me falta que floten
