### ISSUE TITLE
Generar dockerfile

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/django-quilla-web#146]
# Generar dockerfile

## Comportamiento esperado

Ofrecer la posibilidad de instalación a través de docker para permitir que miembros que sepan usar docker puedan hacer una instalación rápida del proyecto

**Comment by andresperezcera** [comment]
Respuesta a: ¿Cómo exponer carpetas de trabajo locales al container de Lektor CMS en windows? [Respuesta](https://rominirani.com/docker-on-windows-mounting-host-directories-d96f3f056a2c). Solo haría falta este mismo procedimiento en Ubuntu y listo.

**Comment by Scot3004** [comment]
@andresperezcera me gusta ese workaround, en cuanto a la imagen que pase, crees que alli aplica mas un docker-compose.yml o un Dockerfile

**Comment by andresperezcera** [comment]
@Scot3004 Lo que sé de docker es lo que leí en 2 horas, pero creo que sea lo que sea hay que controlar el ambiente exacto en el que trabajarán las personas y proveer comandos a prueba de tontos. No porque sean tontos, sino porque los que no sabemos de algo y queremos probarlo nos toca de esa manera.

**Comment by Scot3004** [comment]
Entonces mejor generar uno nuevo

**Comment by javierdaza** [comment]
De acuerdo

**Comment by jaraujoduarte** [comment]
@javierdaza este ticket todavia es de interes para la comunidad (no ha habido movimiento en unos meses)? Si lo es, yo puedo contribuir.

**Comment by Scot3004** [comment]
@jaraujoduarte este ticket aun es de interes para la comunidad, excelente, son bienvenidas tus contribuciones, ten presente la guia en https://github.com/PyBAQ/django-quilla-web/blob/master/CONTRIBUTING.md y esperamos tu Pull request
