### ISSUE TITLE
Eventos deberia tener un tipo de datos estructurados

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/django-quilla-web#152]
# Eventos deberia tener un tipo de datos estructurados
## Comportamiento esperado

Los eventos actualmente cumplen con la estructura
- Año
- Numero de la charla
- Fecha
- Titulo
- Anexos

Deberia crearse un model para poder gestionar los mismos, ademas de migrar los contenidos actuales a dicha estructura

## Comportamiento actual

Los eventos toca agregarlos manualmente en una tabla ubicada en el archivo [content/eventos/contents.lr](https://github.com/PyBAQ/django-quilla-web/blob/master/content/eventos/contents.lr)

**Comment by andresperezcera** [comment]
No sería efectivo, en ese caso, un [Flow Block](https://www.getlektor.com/docs/content/flow/) que permita simplemente ingresar ítems en esa tabla? Sería más fácil de ingresar la información así, ¿no?

**Comment by Scot3004** [comment]
Si y no
Si se tienen esos datos como models incluso se podria crear una galeria por cada uno de ellos o agregar cualquier otro tipo de detalle, por otro lado como por meetup son 2 charlas puede que solo sea una parte de un trabajo mas grande.
El flowblock funcionaria perfecto para lo que se tiene actualmente, Aunque creo que se quedaria corto si se quiere llegar al nivel de detalle que mencione anteriormente.
(postdata, los flowblocks tambien tienen models)

**Comment by javierdaza** [comment]
Entiendo. Lo adecuado sería brindar más detalle pero los pocos voluntarios que tenemos no dan a basto con todas las tareas.

**Comment by Scot3004** [comment]
La idea con esta tarea es poder facilitar el ingreso de nuevas charlas a traves del dashboard de lektor, en otras palabras, ademas de permitir invertir el flujo actual de las charlas mas viejas primero y colocar las mas nuevas, si asi se quisiera, todo esto de forma automatizada

**Comment by Scot3004** [comment]
Esta tarea debería hacerse usando el api de Meetup al compilar el sitio de lo contrario tocaria crear manualmente los registros cada vez que se anuncie un nuevo meetup

**Comment by Scot3004** [comment]
Update: #188 consulta el API de meetup, para resolver este issue deberia seguirse con esa idea, los actuales anexos no estan cubiertos por dicha API por ende tocaria crear otro databag, este si toca alimentarlo manualmente asociando el identificador de meetup con el respectivo adjunto

**Comment by Scot3004** [comment]
@javierdaza estas de acuerdo con mi anterior comentario sobre este issue?

**Comment by Scot3004** [comment]
@andresperezcera tenias razón sobre usar flowblock :stuck_out_tongue_closed_eyes: aunque es automatizado si se llama al api de meetup, por otro lado pasar lo que ya esta, va a ser una tarea dolorosa :sob:

**Comment by andresperezcera** [comment]
Si ya tienes el modelo, dejame ayudar, a veces necesito esas tareas repetitivas para bajar el estrés. Es la hora y aun no comienzo la parte de proyectos.

**Comment by Scot3004** [comment]
Hagamos algo, yo te subo un ejemplo con las ultimas 3 charlas, y te dejo el resto a ti :1st_place_medal: así como hicimos la guía de instalación

**Comment by andresperezcera** [comment]
Perfecto, me parece bien. Pero haz el pull tu con el ejemplo, yo saco los datos del comit anterior.

**Comment by Scot3004** [comment]
@andresperezcera ya hice el ejemplo, aunque cargue de una vez todo el contenido :sweat_smile:
