### ISSUE TITLE
Agregar Sergio como colaborador

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/django-quilla-web#156]
# Incidente sitio web python Barranquilla

## Comportamiento esperado

Sergio Orozco deberia aparecer en la sección de colaboradores en algo relacionado con el sitio web

![img_20180209_173354038](https://user-images.githubusercontent.com/1175402/46777983-46a42e80-ccd7-11e8-931f-297f85ce3195.jpg)

## Comportamiento actual

![imagen](https://user-images.githubusercontent.com/1175402/46777671-e9f44400-ccd5-11e8-8c30-7cb1a532920d.png)

Solo aparece Javier Fonseca

## Pasos para reproducir el error

1. Abrir pagina Nosotros
1. Ir a la sección Colaboradores

**Comment by javierdaza** [comment]
¿Qué le colocamos debajo del nombre?

**Comment by Scot3004** [comment]
Escoje alguna de este sitio web :smile: 
https://www.secorto.com/portafolio/pybaq

**Comment by javierdaza** [comment]
404

**Comment by javierdaza** [comment]
Envía el PR para esto por fa @Scot3004

**Comment by Scot3004** [comment]
Eso haré :D yey

**Comment by javierdaza** [comment]
Título debe ser *Contribuidor sitio web*
