### ISSUE TITLE
Manejo de assets presenta inconvenientes para nuevos contribuidores

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/django-quilla-web#166]
# Incidente sitio web python Barranquilla

## Comportamiento esperado

Deberia actualizarse las dependencias node del proyecto debido a que al dia de hoy estan sin soporte

## Comportamiento actual

El proyecto usa la versión ^1.13.1 de webpack, sin embargo ya hoy dia se usa la versión 4

**Comment by javierdaza** [comment]
Cnnclusión: Desinstalar webpack y usar solo lektor

**Comment by GudarJs** [comment]
Me puedo pedir este?
