### ISSUE TITLE
Agregar colaborador

### ISSUE THREAD

**Issue by javierdaza** [PyBAQ/django-quilla-web#173]
# Incidente sitio web python Barranquilla

## Comportamiento esperado

Andrés Pérez debería aparecer en la página web como colaborador. El título debe ser *Contribuidor y traductor*
Similar a https://github.com/PyBAQ/django-quilla-web/issues/156

![andresperezcera](https://user-images.githubusercontent.com/3085051/47251653-f413f200-d3fb-11e8-8d55-ed58d5ae2526.png)

**Comment by ederius** [comment]
Empezare a trabajar sobre esta tarea
