### ISSUE TITLE
Subir patrocinador Monokuko Space a Hacktoberfest 2018

### ISSUE THREAD

**Issue by javierdaza** [PyBAQ/django-quilla-web#182]
## Comportamiento esperado

Mostrar imagen de patrocinador en el landing de Hacktoberfest 2018. Necesitamos la img en el landing

![mkk_perfil 1](https://user-images.githubusercontent.com/3085051/47366988-627add80-d6a4-11e8-82f2-b7f0759d7a2f.jpg)

**Comment by edgarMejia** [comment]
¿Lo necesitan en https://github.com/PyBAQ/django-quilla-web/tree/master/assets/hacktoberfest2018_assets ?
