### ISSUE TITLE
Migrar boostrap 3 a una nueva versión

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/django-quilla-web#189]
# Solicitud de mejora en sitio web PyBAQ

Cambiando las clases de bootstrap 3 a bootstrap 4

## Ventajas

Reduce la deuda tecnica y ademas usa técnicas mas recientes en desarrollo web

## Desventajas

Es un proceso demorado y puede que algunas clases css que ya funcionen dejen de funcionar (es un cambio mayor)

**Comment by Scot3004** [comment]
Y si mejor creamos una nueva plantilla, aunque necesitamos quien la diseñe :fearful:

**Comment by javierdaza** [comment]
Por ahora se mantiene. La prioridad es poder manejar español e inglés por lo que te comenté

**Comment by javierdaza** [comment]
Close by inactivity
