### ISSUE TITLE
Editar pagina de inicio

### ISSUE THREAD

**Issue by javierdaza** [PyBAQ/django-quilla-web#2]
Editar informacion y estilos de la pagina de inicio

**Comment by javierdaza** [comment]
Me falta pedir ayuda a algún diseñador con los logos de los patrocinadores

**Comment by Scot3004** [comment]
Puedes plantearte una single page app
[Agency theme](http://startbootstrap.com/template-overviews/agency/)
[Creative](http://startbootstrap.com/template-overviews/creative/)
[FreeLancer](http://startbootstrap.com/template-overviews/freelancer/)

**Comment by Scot3004** [comment]
Aclaro, eso no lo hace incompatible, por ejemplo [mi blog](http://scot3004.github.io) tiene los [posts](http://scot3004.github.io/blog) por aparte de la página de inicio

**Comment by javierdaza** [comment]
Gracias! Ya tenemos una plantilla @Scot3004
