### ISSUE TITLE
Código de conducta

### ISSUE THREAD

**Issue by javierdaza** [PyBAQ/django-quilla-web#201]
# Solicitud de mejora en sitio web PyBAQ

El [código de conducta ](https://github.com/PyBAQ/codigo-de-conducta)debe verse visible en la página web. 

## Ventajas

Poder aplicar a mas patrocinios con la PSF y que la comunidad vea las reglas de comportamiento en un lugar mas visible que el repositorio

**Comment by Scot3004** [comment]
@javierdaza necesitamos una versión en ingles del código de conducta, tomamos este? 
https://www.djangoproject.com/conduct/

**Comment by javierdaza** [comment]
Si, puede ser. ¿Tu que opinas @andresperezcera ?

**Comment by andresperezcera** [comment]
Con gusto creo una versión en inglés directamente traducida de la versión en español. Aún cuando es originalmente traducida del inglés en su mayor parte, creo que hicimos algunos ajustes. Lo veo y realizó el cambio necesario.
