### ISSUE TITLE
Crear databags para los menús

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/django-quilla-web#203]
# Solicitud de mejora en sitio web PyBAQ

Uno de los pasos para facilitar la internacionalización es tener los menús en un lugar parametrizable, segun ejemplos que vi el lugar recomendado son los databags

## Ventajas
Facilita la internacionalización que se quiere conseguir

**Comment by javierdaza** [comment]
¿Cómo vamos con esto @Scot3004 ?
