### ISSUE TITLE
Agregar los anexos para las presentaciones del 2019

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/django-quilla-web#208]
# Presentaciones pendientes

- [ ] Conociendo Oauth2 + Python para principiantes: Dónde empezar
- [ ] Procesamiento de imágenes de tejido con Python + Project Management 101
- [ ] Capturando credenciales en Google Chrome con DRF & DRF + ElasticSearch
- [ ] Multimodal video analytics + Data Science & the New Age Revolution
- [ ] ¿Y si hacemos un skype? + Primeros pasos en Numpy
- [ ] Inteligencia Artificial y sus Aplicaciones + Ciberseguridad: Vectores de Ataque
- [ ] App serverless y auto escalable con AWS Lambda + Consigue un trabajo en dólares
- [ ] Estudiar Machine Learning en el Exterior+ Intro a la Visión por Computador
- [ ] Un algoritmo artístico de estilo neural + PyBAQ: Detrás del escenario
- [ ] Crea un sitio web en tiempo real tipo Google doc + Creando comunidades exitosas
- [ ] Finanzas cuantitativas para análisis de mercados + App del manto de la Tierra
- [ ] Bienvenida 2019 y reunión abierta equipo PyBAQ

**Comment by javierdaza** [comment]
Estos son los enlaces. ¿Quien me puede ayudar a subirlos?

- Inteligencia Artificial y Aplicaciones: https://drive.google.com/file/d/1Mk99-prLjBfmpF9CDpnw_xIhftfv3k4a/view?usp=sharing
- Ciberseguridad: https://drive.google.com/file/d/1BA4cowactgoOEvaMWeqzkHAH1HSKnoGo/view?usp=sharing
- Serverles: https://drive.google.com/file/d/1paeQ69ycefeRzdFJrPBqZiFN5MJgP6Ar/view?usp=sharing
- Consigue trabajo en Dolares: https://drive.google.com/file/d/1vEDU9LV8XD_dWcEN8GopGVEKfssfhPHS/view?usp=sharing
- Estudiar Machine Learning en el exterior: https://drive.google.com/file/d/1cXumlUM4gmbVbSYEG3z1PUgowVVzt5_5/view?usp=sharing
- Intro de visión por computador:
https://drive.google.com/file/d/1XmMDzjxphOHgZUDM348Cyl0xTmfXplka/view?usp=sharing
- PyBAQ detrás del escenario: https://drive.google.com/file/d/1Ot6W_wCsk8R4eSPIhVnp-9Q6SaPwI3Wl/view?usp=sharing
- Creando comunidades exitosas: https://docs.google.com/presentation/d/1Nk4lRdtKiGHHSQYnAJSeOso_vN0T1hP3Qg1BwtWM544/edit?usp=sharing

-----
*Presentaciones Pendientes*
- Finanzas cuantitativas para análisis de mercados
- App del manto de la Tierra
- Crea un sitio web en tiempo real tipo Google doc
- Un algoritmo artístico de estilo neural

**Comment by javierdaza** [comment]
@Scot3004 help

**Comment by Scot3004** [comment]
@javierdaza creamos un nuevo issue para las del segundo semestre o que se anexen en el mismo pr?

**Comment by javierdaza** [comment]
Todos se anexarán acá. ¿@pandrearro puedes ayudarnos con los enlaces de google drive?

**Comment by pandrearro** [comment]
- Conociendo Oauth2 + Python para principiantes: Dónde empezar:
 Conociendo Oauth2: https://drive.google.com/file/d/1_UQB0yA2ndhcxW-1hu1JPyBElNESuOLV/view?usp=sharing
  Python para principiantes: 
- Procesamiento de imágenes de tejido con Python + Project Management 101
  Project Management 101: https://drive.google.com/file/d/1B3tUl68eJCa19B9SA99UuFi_H4opJZQ6/view?usp=sharing
- Capturando credenciales en Google Chrome con DRF & DRF + ElasticSearch:
ElasticSearch: https://drive.google.com/file/d/1Ul6RinnwuHrss5MlnNiTAsz6hAL0Jbtj/view?usp=sharing

**Comment by jorueda** [comment]
Buenos días, pueden confirmarme un poco más en qué consiste este Issue? Es corregir los enlaces en alguna página o es adicionarlos en alguna página? Gracias y saludos.

**Comment by Scot3004** [comment]
Mira esta pagina, asi se ven los eventos del 2018

![imagen](https://user-images.githubusercontent.com/1175402/89342074-e0d12580-d667-11ea-8b46-6ffce905a36c.png)

Puede verse que abajo de las fechas se ven unos enlaces a los archivos anexos como serian slides, repositorios con código etcétera

Ahora sube un poco en la misma pagina y mira como se ven los eventos de 2019

![imagen](https://user-images.githubusercontent.com/1175402/89342241-1d048600-d668-11ea-9db3-47c4803f2dcf.png)

No se ve ningún anexo ni a imágenes ni demás, esos son los enlaces compartieron como comentario en este issue.

En eso consiste este issue, esto se puede actualizar en la página de eventos.
