### ISSUE TITLE
Documentar como se pueden crear traducciones de una página

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/django-quilla-web#213]
# Solicitud de mejora en sitio web PyBAQ

Para poder realizar las tareas de traducción se hace necesario especificar como se crean los contenidos alternativos, ademas de explicar en terminos generales como se usan los bloques flexibles

**Comment by Scot3004** [comment]
@javierdaza tengo un tiempo para trabajarle a esto, sera que lo ponemos en el README o sale mejor como un blog post?

**Comment by javierdaza** [comment]
@Scot3004 el README ya esta bien largo. Coloquemos un enlace hacia una wiki de Github ¿qué opinas?

**Comment by Scot3004** [comment]
por eso mismo la pregunta ;)

**Comment by Scot3004** [comment]
Imagenes

Original page
![imagen](https://user-images.githubusercontent.com/1175402/107145195-fde3fb00-690d-11eb-8a4c-c19c6e695a6f.png)

Click on languaje switcher
![Screenshot_20210207_062706](https://user-images.githubusercontent.com/1175402/107145196-050b0900-690e-11eb-949d-c2590699a83d.png)

New page with previous contents
![imagen](https://user-images.githubusercontent.com/1175402/107145214-2966e580-690e-11eb-9507-570bcf73c20a.png)

Final result
![imagen](https://user-images.githubusercontent.com/1175402/107145461-929b2880-690f-11eb-8166-efd702a159d4.png)

**Comment by Scot3004** [comment]
@javierdaza me gustaria que revises la wiki https://github.com/PyBAQ/django-quilla-web/wiki/Traducir-una-p%C3%A1gina para subir las imagenes toca hacerlo con un issue (use este para dicho fin).

Si tienes algun comentario, actualiza los cambios y por favor me comentas que cambios realizaste

**Comment by Scot3004** [comment]
actualizada wiki según unas sugerencias recibidas por parte de @jorueda

**Comment by Scot3004** [comment]
@jorueda me colaboras con otra revisión y me cuentas si podemos cerrar este ticket

**Comment by jorueda** [comment]
Buenas tardes @Scot3004 , encontré dos pequeñas correcciones, colocar el `Va` en mayúscula después del punto, y el archivo contents+en.lr parece tener unos caracteres `_` de más:

en la pagina a traducir. `va` a notar
Al​ Guardar los cambios​, se creará un nuevo archivo `_`contents+en.lr`_`​

**Comment by jorueda** [comment]
@Scot3004 , encontré la manera de editar directamente los cambios en el Wiki y ¡quedaron corregidos los cambios!. Ya se puede cerrar.

**Comment by pyjavo** [comment]
Pregunta @Scot3004 Si yo quiero escribir un artículo **solo en inglés** ¿es posible? o ¿debo escribirlo en ambos idiomas?

**Comment by Scot3004** [comment]
Puedes escribirlo solo en inglés, lo que no se es como ocultarlo para el blog en español y mostrarlo en inglés y viceversa

**Comment by Scot3004** [comment]
Creo que con lo que tenemos se puede cerrar https://github.com/PyBAQ/django-quilla-web/wiki/Traducir-una-p%C3%A1gina allí se puede encontrar la información discutida en este ticket
