### ISSUE TITLE
Usar flowblocks en la página de contacto

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/django-quilla-web#215]
# Solicitud de mejora en sitio web PyBAQ

## Vista de como se administra la página de nosotros

![Screenshot_20190607_015623](https://user-images.githubusercontent.com/1175402/59436144-a26a0e80-8db4-11e9-804a-1cf51792cbf3.png)

## Estado actual
![imagen](https://user-images.githubusercontent.com/1175402/59436249-de9d6f00-8db4-11e9-8a3c-64e5c9aca86a.png)

![imagen](https://user-images.githubusercontent.com/1175402/59436386-202e1a00-8db5-11e9-9a88-70f530af3658.png)

![imagen](https://user-images.githubusercontent.com/1175402/59436335-07256900-8db5-11e9-996f-7f3b8f2727f9.png)

**Comment by javierdaza** [comment]
Esta tarea queda pendiente mientras Brayan agrega los enlaces para las encuestas de futuros ponentes, escritores y voluntarios
