### ISSUE TITLE
Actualizar el consumo del API de meetup

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/django-quilla-web#216]
# Error en sitio web de python Barranquilla

## Comportamiento esperado

![imagen](https://user-images.githubusercontent.com/1175402/59545830-18bc5d00-8eea-11e9-8055-75bf33b07ff6.png)

Esta vista deberia seguir funcionando despues del 15 de agosto

## Comportamiento actual

Me llego al correo esta advertencia, el sitio web actualmente usa api key ademas de api v2 :sob: 

![imagen](https://user-images.githubusercontent.com/1175402/59545801-c713d280-8ee9-11e9-9192-64def9926c22.png)

**Comment by Scot3004** [comment]
Nos queda un mes para esta tarea

**Comment by Scot3004** [comment]
Este issue se abordara haciendo que el cargue de los eventos sea manual

**Comment by krthr** [comment]
Puedo ayudar a migrar a la versión 3 de la API. ¿O existe algún problema con la v3?

**Comment by Scot3004** [comment]
Seria excelente si colaboras con un script que traiga los eventos

de momento ya tengo identificado algunas acciones que puede hacer ese script

- 1 Consumir oauth2
- 2 A la peticion hay que especificarle que traiga los featured images, por defecto el endpoint de events no lo trae
- 3 El json que trae como respuesta se debe transformar, debido a que de momento los databags no soportan listas como elemento raiz y la api v3 de meetup lo retorna asi
- 4 Puede ser un databag (como esta funcionando ahora) o si quieres aprender mucho mas generar un contents.lr con cada evento el cual permitiria editar los eventos una vez cargados con el importar eventos eso si, el script debe poder ser capaz de saber cuales eventos ya fueron agregados y cuales faltan por agregar, o bien importar a partir de una fecha

**Comment by krthr** [comment]
> * Consumir oauth2

Si queremos evitar el OAuth2, podríamos hacer scraping.

**Comment by Scot3004** [comment]
pues si, pero me gusta mas la idea de oauth, un scrapper tiende a depender del diseño de la página

**Comment by javierdaza** [comment]
Concuerdo con @Scot3004 Usemos oauth
