### ISSUE TITLE
Presentacion En Post Beneficios tributarios para el sector TIC no carga

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/django-quilla-web#237]
# Error en sitio web de python Barranquilla

## Pasos para reproducir el error

1. Ingresar a la pagina https://pybaq.co/blog/beneficios-tributarios-para-el-sector-tic/
2. Buscar la presentación al final de la pagina

## Comportamiento esperado

La presentación debería poder mostrarse o bien el enlace para poder visualizarla

## Comportamiento actual
![image](https://user-images.githubusercontent.com/1175402/80017056-956c8000-8499-11ea-88f1-5b873bf0620a.png)
Presentación del tema no se puede visualizar

**Comment by jorueda** [comment]
Buenas tardes. Por favor si me pueden confirmar el enlace correcto de la presentación, el que aparece en el código está incorrecto. Entré a esa charla en Meetup pero tampoco aparece el enlace. Gracias.

**Comment by javierdaza** [comment]
@jorueda este es el enlace https://docs.google.com/presentation/d/1dgN1RklmS8y_TJsgjpOCfBan5ts8G7t96tIK_Lyb-ok/edit?usp=sharing
