### ISSUE TITLE
Algunas imagenes no se cargan en el post ¿Cómo fue organizar el primer Django Girls Barranquilla?

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/django-quilla-web#238]
# Error en sitio web de python Barranquilla

## Pasos para reproducir el error

1. Abre la pagina https://pybaq.co/blog/como-fue-organizar-primer-django-girls-barranquilla/
2. Inspecciona las imagenes del sitio web

## Comportamiento esperado

Todas las imagenes deberian cargar correctamente

## Comportamiento actual

Algunas imagenes no se cargan
![image](https://user-images.githubusercontent.com/1175402/80020991-812b8180-849f-11ea-819c-6a743b5d6520.png)

**Comment by javierdaza** [comment]
Hay que cambiar la ruta hacia las que aparecen en esta galería
https://argentinaenpython.com/galeria/django-girls-barranquilla/2017/

O descargar nosotros las imágenes y subirlas al repo

**Comment by Scot3004** [comment]
La verdad me gusta mas la idea de descargar las imagenes
