### ISSUE TITLE
Agregar información cuando se busque ponentes en la pagina de eventos

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/django-quilla-web#244]
# Solicitud de mejora en sitio web PyBAQ

Agregar el siguiente texto a la invitación a presentar charlas

Entre las ventajas que puedo listar para hacerlo se encuentran:
  - Tu charla quedará grabada para compartir o subir a tu portafolio.
  - Es una buena practica de habilidades blandas.
  -  Darte a conocer a ti o a tu proyecto.
  -  Compartir con la comunidad.
  -  Devolverle un poco a la comunidad de lo mucho que nos da gratis día a día.

Pueden haber más beneficios pero esos son los que se me ocurren por el momento. Les dejo el enlace para postularse:

https://forms.gle/tCsALqG2aQ9A1GqD8

Para las personas que quieran ser voluntarios o escribir artículos, les dejo los demás formularios publicados en nuestra página de contacto https://pybaq.co/contacto/

## Ventajas

La información seria mucho mas clara

## Desventajas

Toca revisar la que ya esta compartida

**Comment by javierdaza** [comment]
@bgarcia92 ¿qué opinas?

**Comment by bgarcia92** [comment]
@javierdaza @Scot3004 ayer vi el issue y me parece interesante, podriamos tener una sección mejor estructurada, más llamativa y con más contenido

**Comment by Scot3004** [comment]
Si es que vi el comentario de Javier y pensé, esto debe estar en el sitio web, de hecho puse un mensaje cortito cuando no hay eventos futuros solo es actualizar los eventos

**Comment by bgarcia92** [comment]
Si vamos a mejorar la sección de contactos con todo esto, me apunto

**Comment by Scot3004** [comment]
No habia pensado en eso pero me gusta, proceda compañero
