### ISSUE TITLE
Diapositivas faltantes 2020

### ISSUE THREAD

**Issue by pyjavo** [PyBAQ/django-quilla-web#266]
# Solicitud de mejora en sitio web PyBAQ

Faltaron la diapositivas de como escalar tu infraestructura y la de la charla de GeoDjango

## Ventajas

Completar diapositivas del año 2020

**Comment by jorueda** [comment]
Si se tienen los enlaces a los recursos puedo tomar este issue.

**Comment by pyjavo** [comment]
No se tienen 😕. La ayuda que necesitamos incluye pedirle las ppts a los ponentes en slack.
Para geoDjango es Oswal y para la escalar tu infraestructura la persona fue Jesús Diaz (ambos en el slack de la comunidad)
