### ISSUE TITLE
Adicion nuevos canales de WhatsApp y Telegram a la pagina

### ISSUE THREAD

**Issue by jorueda** [PyBAQ/django-quilla-web#269]
# Solicitud de mejora en sitio web PyBAQ

Adicionar los nuevos canales de WhatsApp y Telegram a la pagina web.

## Ventajas

Incrementar la comunicación entre los miembros de la comunidad de Python Barranquilla.

## Desventajas

Ninguna.

![Redes sociales](https://user-images.githubusercontent.com/45174468/108271420-c90e4a00-713e-11eb-8ec8-7c3656621887.png)

**Comment by pyjavo** [comment]
@jorueda estos son los enlaces:

- http://bit.ly/pyBAQ-whatsapp
- http://bit.ly/pyBAQ-telegram
