### ISSUE TITLE
Actualizar fotos en sección de nosotros

### ISSUE THREAD

**Issue by pyjavo** [PyBAQ/django-quilla-web#272]
# Solicitud de mejora en sitio web PyBAQ

Se deben cambiar las fotos de Sara y Yudy por la del sr @jorueda 

## Ventajas

Tener el equipo actualizado

## Desventajas

Se pierde el registro de las personas que han colaborado de una u otra forma en el pasado

**Comment by Scot3004** [comment]
Se puede tener una mención en la parte inferior, que solo los nombre sin dar mas detalles y con eso evitamos esa desventaja

**Comment by pyjavo** [comment]
¿Una lista con los nombres? ¿Así?

1. Cesar Herdenez
2. Dario Guzmán
3. Sara Galván
4. Yudy Herrera
5. Kathy Lora
