### ISSUE TITLE
Usar python 3 para la imagen docker

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/django-quilla-web#275]
# Solicitud de mejora en sitio web PyBAQ

Actualizar el fichero docker a la versión 3 de python preferiblemente python 3:slim-buster

## Ventajas

La imagen slim buster es mas ligera que la que se está usando actualmente
Ademas que podriamos agregar el script de descarga que está desarrollado usando python 3
Ahora la versión de python recomendada es python 3 https://www.getlektor.com/docs/installation/

## Desventajas

No veo desventajas, ese archivo esta viejo y toca dedicarle su rato 🗡️

**Comment by jorueda** [comment]
Me interesa éste issue. ¿Es sólo editar el Dockerfile y cambiar la línea FROM python:2.7 a FROM python3:slim-buster?

**Comment by pyjavo** [comment]
Y probar que nada se rompa. Asé es @jorueda
