### ISSUE TITLE
Corrección datos en el código de conducta

### ISSUE THREAD

**Issue by pyjavo** [PyBAQ/django-quilla-web#284]
# Error en sitio web de Python Barranquilla

## Comportamiento esperado

El nombre es Python Barranquilla y el correo actual djangoquilla@gmail.com

## Comportamiento actual

"Este código de conducta aplica a todos los espacios administrados por el proyecto Django Barranquilla."

"Sea respetuoso ... Los miembros de la comunidad de Django Barranquilla deben ser respetuosos..."

"La fortaleza de Django Barranquilla viene de su comunidad variada,..."

Segundo, corregir el correo en "Si cree que alguien está violando el código de conducta, les pedimos que lo reporte enviando un correo a organizadores@pybaq.co"

## Pasos para reproducir el error

1. En la URL https://pybaq.co/codigo-de-conducta/ aparecen 2 datos erróneos.

**Comment by Scot3004** [comment]
Entonces el correo organizadores@pybaq.co se usa para reportar incidencias con personas en la comunidad.
Me queda una duda para que se usa el correo djangoquilla@gmail.com ? el cual se menciona en la pagina de contacto y eventos

**Comment by pyjavo** [comment]
Alrevés. El correo organizadores@pybaq.co no existe. El correo es djangoquilla@gmail.com
