### ISSUE TITLE
Nuevo diseño

### ISSUE THREAD

**Issue by pyjavo** [PyBAQ/django-quilla-web#290]
# Solicitud de mejora en sitio web PyBAQ

Nuevo diseño.

## Ventajas

- Tenga librerías de frontend más actualizados (plantilla en bootstrap, material UI o que use tailwindCSS)
- SEO
- La página de inicio tenga más diseño

## Desventajas

No tiene WAI-ARIA porque serían más tests

**Comment by jorueda** [comment]
¿En qué consiste este Issue? ¿Se debe instalar una nueva librería o actualizar una existente?

**Comment by pyjavo** [comment]
@jorueda está en decisión con @Scot3004 básicamente es 1. un nuevo diseño o 2. el mismo con bootstrap actualizado y que permita modificar el css fácilmente

**Comment by pyjavo** [comment]
Ya lo hablamos. Compraremos una nueva plantilla (sencillita en HTML)

**Comment by pyjavo** [comment]
Copio el mensaje de @Scot3004 

Este es el tema usado en la pagina, https://dribbble.com/shots/1517938-Solid-Bootstrap-3-Theme 
Sin embargo, sugiero en lugar de pensar en una plantilla generica, continuar con un diseño personalizado, basandome en que gran parte de los estilos del sitio web son personalizados sobre boostrap 3, en su lugar recomiendo, pasar lo que tenemos a boostrap 5 y usar las variables de sass para personalizar los estilos
