### ISSUE TITLE
Problema con el Javascript y CSS en la seccion de nostros

### ISSUE THREAD

**Issue by javierdaza** [PyBAQ/django-quilla-web#30]
Antes uno colocaba el mouse sobre la foto y salia una ventana verde con los 2 iconos. Ahora solamente sale un bloque verde gigante debajo de la foto

![pjimage](https://cloud.githubusercontent.com/assets/3085051/26082941/30c6de42-3998-11e7-9c24-d9b8d07764f6.jpg)

**Comment by Scot3004** [comment]
Corregido en #47

**Comment by javierdaza** [comment]
Se volvió a dañar la sección **organizadores**, específicamente el botton de **twitter**. 

Fue un error que introdujo el PR -----> #51
<img width="318" alt="captura de pantalla 2017-06-17 a las 3 13 26 p m" src="https://user-images.githubusercontent.com/3085051/27256014-c5c793b0-536f-11e7-90ce-ac2d1eb18402.png">

**Comment by javierdaza** [comment]
cerrado por @Scot3004 en a00f27fab5eb62e6f06bcdb18bc834035277bc24
