### ISSUE TITLE
Actualizar lektor y flask

### ISSUE THREAD

**Issue by pyjavo** [PyBAQ/django-quilla-web#309]
# Solicitud de mejora en sitio web PyBAQ

No esta funcionando el build y al parecer está relacionado con paquetes deprecados

## Ventajas

Poder construir el build en travis

## Desventajas

Verificar que los paquetes para test no estén deprecados también

**Comment by jorueda** [comment]
Cuando se ejecuta el proyecto en Docker muestra el siguiente error:
```
docker run --rm -p 5000:5000 -v ${PWD}:/app --name pybaq-local pybaq
Traceback (most recent call last):
  File "/usr/local/bin/lektor", line 5, in <module>
    from lektor.cli import main
  File "/usr/local/lib/python3.10/site-packages/lektor/cli.py", line 11, in <module>
    from .utils import secure_url
  File "/usr/local/lib/python3.10/site-packages/lektor/utils.py", line 28, in <module>
    from werkzeug.posixemulation import rename
ModuleNotFoundError: No module named 'werkzeug.posixemulation'
```
No sé si tenga que ver con este cambio.
