### ISSUE TITLE
Icono de Linkedin

### ISSUE THREAD

**Issue by pyjavo** [PyBAQ/django-quilla-web#323]
# Solicitud de mejora en sitio web PyBAQ

Falta el enlace hacia la página de Linkedin de la comunidad https://www.linkedin.com/company/35621495/admin/

## Ventajas

Mostrar que tenemos página en Linkedin

## Desventajas

Ubicar nuevo icono en el footer

**Comment by Scot3004** [comment]
Una pregunta por que no ponerlo con un nombre mas bonito, por ejemplo https://www.linkedin.com/company/perficient/

**Comment by pyjavo** [comment]
@Scot3004 porque no se como se hace jajajajajaaj. ¿Sabes como se hace? Cualquier ayuda es cariño

**Comment by Scot3004** [comment]
Parece que el enlace a usar en ese issue es este https://www.linkedin.com/company/python-barranquilla/
