### ISSUE TITLE
Editar página de blog

### ISSUE THREAD

**Issue by javierdaza** [PyBAQ/django-quilla-web#5]
Editar contenido, texto, imágenes y CSS.
- [ ] Blog post
- [ ] Blog general

**Comment by Scot3004** [comment]
Esto puede resolverse una vez implementes lektor, lo que restaria es que la template sea consistente al resto de la página

**Comment by Scot3004** [comment]
Una observación, puedo colocarlo a funcionar con la template actual, sin embargo, hay cosas que deben ser revisadas, hay ciertos antipatrones en los css que hay que corregir.

**Comment by Scot3004** [comment]
Así que en lo personal, creo que hay que hacerlo como está, y luego hacer un refinamiento pasándole linters al código para que alí quede claro que cosas hay que corregir.
