### ISSUE TITLE
Adicionar formulario de contacto.

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/django-quilla-web#54]
Existen herramientas que permiten el envio de correos al recibirlo en un formulario, o bien un servicio sencillo corriendo en algun lugar con cors configurado para aceptar peticiones unicamente del sitio de pybaq

**Comment by javierdaza** [comment]
No creo que haga falta. Pensaba mas bien poner las redes sociales debajo del texto. ¿Tu que opinas @Cesar0510 ?

**Comment by Cesar0510** [comment]
esa parte no es necesaria para eso tenemos las redes sociales. FB TW y meetup, si se necesita algo mas ps se hacer por medio de un google form o solo se pone un correo de contacto. 
** con las redes sociales es mas que suficiente.**

**Comment by javierdaza** [comment]
Alguna cosa podemos usar este servicio http://www.emailjs.com/ (es una sola linea de javascript)
