### ISSUE TITLE
Al agregar algunas etiquetas HTML se dañan las imagenes

### ISSUE THREAD

**Issue by javierdaza** [PyBAQ/django-quilla-web#63]
No puedo usar ni `<i><i> ni <p style=“font-style: italic;“></p> `porque daña la página

![pasted image at 2017_07_19 09_31 am](https://user-images.githubusercontent.com/3085051/28372440-534abc0e-6c65-11e7-81d1-d4bb9213a114.png)

**Comment by Scot3004** [comment]
Prueba con:
 *Texto en italica*  _texto en italica_
`*Texto en italica*  _texto en italica_`
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#emphasis

**Comment by javierdaza** [comment]
Gracias. Esto se resolvió mediante el uso apropiado del Markdown
