### ISSUE TITLE
Meta tags para Facebook y Twitter

### ISSUE THREAD

**Issue by javierdaza** [PyBAQ/django-quilla-web#73]
Agregar metatags para redes sociales en el HTML

**Comment by Scot3004** [comment]
Eso tiene que ver con esto http://ogp.me/

**Comment by javierdaza** [comment]
Si @Scot3004 y el de twitter tambien

**Comment by javierdaza** [comment]
<img width="563" alt="captura de pantalla 2017-10-23 a las 8 35 55 a m" src="https://user-images.githubusercontent.com/3085051/31891947-6826909a-b7cd-11e7-8d7d-e7f73ad7a5d1.png">
<img width="1016" alt="captura de pantalla 2017-10-23 a las 8 37 06 a m" src="https://user-images.githubusercontent.com/3085051/31891955-6fdfcb12-b7cd-11e7-9755-5723f44c990b.png">
Esto aún le falta @Scot3004 Las imágenes de cada artículo deben visualizarse. El issue queda abierto de nuevo.
