### ISSUE TITLE
Acomodar logo en versión mobile

### ISSUE THREAD

**Issue by javierdaza** [PyBAQ/django-quilla-web#8]
Media queries en CSS para acomodar el logo.
![djangoquilla-mobile](https://cloud.githubusercontent.com/assets/3085051/15131710/0c2f2692-1618-11e6-9713-e1e07acd8b87.png)

**Comment by Scot3004** [comment]
Eso fue corregido al cambiar la imagen en #27 
![Logo pybaq](https://cloud.githubusercontent.com/assets/1175402/26084730/eb573c2e-39a3-11e7-9c7e-ec4afd545cd8.png)
