### ISSUE TITLE
Crear un artículo que recommiende recursos para aprender Python

### ISSUE THREAD

**Issue by javierdaza** [PyBAQ/django-quilla-web#93]
Sería como un artículo con un listado de recursos. Puntos extra si el articulo es entretenido y utiliza imagenes/GIF para ser fácil de leer

**Comment by andresperezcera** [comment]
Oigan, han trabajado en esto?

**Comment by javierdaza** [comment]
@Cesar0510 estaba trabajando en esto pero no lo termino. https://gist.github.com/Cesar0510/f492b469aa9ca8bcc813017277b22644

¿Lo terminarías?

**Comment by andresperezcera** [comment]
Retomaré el trabajo desde donde quedó. La próxima semana salgo de vacaciones y si no me ocupo en algo me voy a volver loco:
https://gist.github.com/andresperezcera/7e9ae4ed9eb61f8139ba5957e6ea32d4

**Comment by javierdaza** [comment]
¡que bien! @andresperezcera por fa ten en cuenta las sugerencias que hay en los comentarios y la imagen principal del artículo https://gist.github.com/Cesar0510/f492b469aa9ca8bcc813017277b22644

**Comment by andresperezcera** [comment]
Aquí tengo un preliminar, muy a pesar de detestar lo limitado del markdown de github.

https://gist.github.com/andresperezcera/df524ecb4234d7954af14a7e118b98a6

**Comment by javierdaza** [comment]
Perfecto!!! Lo único sería revisar las licencias de las imágenes.

- Si son creative commons, debe hacerse la mención a la original.
- Si son libres, pues....no pasa nada.
- Si tienen copyright o no sabes, lo mejor sería buscar otra que si se pueda compartir.

**Comment by andresperezcera** [comment]
Pues, es obvio que la primera tiene que cambiar (pues es de Disney &mdash;desgraciados), la cambié por esta: 
* [xkcd non-commercial attribution](http://es.xkcd.com/strips/python/)

La segunda es creative commons, incluyo el link:
* [pixabay commons](https://pixabay.com/es/pasos-arena-playa-los-pies-732128/)

:bowtie:  😁

**Comment by javierdaza** [comment]
jajajajaja bien.

Ok, la segunda es [creative commons zero](https://creativecommons.org/share-your-work/public-domain/cc0/) (no es necesario reconocimiento....perfecto)

**Comment by andresperezcera** [comment]
Y ahora?

**Comment by javierdaza** [comment]
Lo que dice en el artículo:

- Proyecto A
- Proyecto B
- Proyecto C

**_¿Era de prueba y en realidad ibas a cambiarlos por proyectos reales o era de forma explicativa?_** Porque pensé que eran de prueba y me puse a buscar proyectos (LOL) y mira lo que encontré:

- [reddit python projects](https://www.reddit.com/r/learnprogramming/comments/6j6jdj/beginner_python_projects/?st=jbr1p1a3&sh=6dc1d314)
- [project list](https://docs.google.com/document/d/1TyqD2_oDtiQIh_Y55J5RfeA91JJECc97xYIKM112H9I/edit) (en uno de los comentarios en reddit)


[El paso que sigue sería este.](https://pybaq.co/blog/contribuir-blog-python-barranquilla/) Recuerda colocar las imágenes en assets. Incluyendo la [imagen principal del artículo](https://user-images.githubusercontent.com/3085051/33140230-5fe780c0-cf7d-11e7-955f-e8c939512566.png)
